# Generated by Django 6.0.3 on 2026-03-30 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='generationrequest',
            index=models.Index(fields=['user', '-created_at'], name='ai_requests_user_id_988af1_idx'),
        ),
        migrations.AddIndex(
            model_name='generationrequest',
            index=models.Index(fields=['status'], name='ai_requests_status_b68e64_idx'),
        ),
        migrations.AddIndex(
            model_name='generationrequest',
            index=models.Index(fields=['-created_at'], name='ai_requests_created_74f839_idx'),
        ),
    ]
