# Generated by Django 5.1.8 on 2026-04-12 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, editable=False, help_text='Avtomatik yaratilgan 8 xonali kod', max_length=8, unique=True, verbose_name='Promokod')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Promokod narxi', max_digits=12, verbose_name="Summasi (so'm)")),
                ('token_count', models.PositiveIntegerField(help_text='Foydalanuvchiga beriladigan tokenlar soni', verbose_name='Token miqdori')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Foydalanilmagan promokod faol bo'ladi", verbose_name='Faolmi')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Ishlatilgan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_promo_codes', to=settings.AUTH_USER_MODEL, verbose_name='Ishlatgan foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Promokod',
                'verbose_name_plural': 'Promokodlar',
                'ordering': ('-created_at',),
            },
        ),
    ]
